server:
  port: 9090
  servlet:
    context-path: /@artifactId@
#    context-path: /hang-bear-home

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_flag  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
