spring.profiles.active: dev


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    #    sql日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: delete_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#logging:
#  level:
#    com.wzh.home.mapper: debug

#spring:
#  main:
#    # Spring Boot 2.1 需要设定
#    allow-bean-definition-overriding: true
#  data:
#    mongodb:
#      # mongo开启auth后需要用户名、密码，不开启则不需要用户名，密码#
#      uri: mongodb://root:cisxa9-dyzwih-sAjwyn@dds-bp1d3fced323bec41.mongodb.rds.aliyuncs.com:3717
#      database: xfwms
